### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by pavezzo** [isakpulkki/15PuzzleSolver#2]
I downloaded the project at 17.2. 16:30 clock. 
The project seems to be working fine and the code looks well organized. 

Few things you could consider:
* Add linting, some of the lines seem a little bit too long and there is trailing whitespace for example
* Fix the color of the moves counter, currently you can't see it:  change bg=BACKGROUND_COLOR to for example bg="white" on lines 61 and 63
* You should decide whether you use type hinting on all the classes.
* You could use list comprehension on class Puzzle, function set_numbers:
	self.board = [[(x * self.size) + (y + 1) for y in range(self.size)] for x in range(self.size)]

**Comment by isakpulkki** [comment]
Thank you for the tips!
