### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by janikakalliokoski** [isakpulkki/15PuzzleSolver#3]
Project cloned 21.2. at 16:33

I started the project and the algorithm seems to work out the shortest path very well. It was a bit confusing that the program writes the time and other info into the console and not the interface the puzzle is in and it took me a while to figure that out :D In my opinion it would be clearer if everything that the user needs to see happened in the same interface. I also noticed that if I click the exit sign in the interface, the program doesn’t end and I have to open the program in another terminal window.

![image](https://user-images.githubusercontent.com/96131752/220411596-6bb2c13e-2163-4e5f-b158-a02d5d18b8c7.png)

The code is clean and well constructed. I like that you have separated the functionalities into own classes and methods. The code is very clear and easy to understand what happens and where. I see no faulty code except the exit sign in the user interface doesn't work correctly.

You don’t have a lot of tests and I would add tests with both invalid and valid events. It seems that you have not tested the IDA* algorithm at all, and even though it seems to work correctly, I would like to see tests that ensure that the algorithm works correctly. I’m sure that this is on your todo list.

It would be nice if a user could modify the size of the puzzle without touching the code, because someone who doesn't know what is going on in the code could easily break it.

All in all it is early on and you have lots of time to do adjustments and more tests. I find this project very interesting and it is nice to follow the algorithm finding the path. Good work and good luck with the rest of the course!

**Comment by isakpulkki** [comment]
Thank you for the tips! :) I noticed that the exit does not work if the program is in the middle of executing the algorithm, but when it is not it works, have to figure that out.
