### ISSUE TITLE
Code Review week 6

### ISSUE THREAD

**Issue by Mvaaras** [isakpulkki/15PuzzleSolver#4]
Downloaded 21:00 26.2.-23

Your code is well formatted and documented, and easy to understand. I was able to run the application and the tests without problems. 

I liked that there was an option to try to solve the puzzle myself, as well as see how the algorithm does it. The algorithm worked fast and found a solution quickly.

Your test coverage is reasonably high and I can see that a lot of the missed parts were edge cases where things are missing which doesn't seem that important to test anyways.

In some parts you have a *lot* of docstring documentation. This is one way to do things, but it might be beneficial to also make the names of your functions and variables as descriptive as you can. This way, your code is easier to read even with less heavy documentation. For example, instead of using 'g' in your IDA* search function, you could name it something more descriptive. Using more descriptive names for generally makes your code easier to read and in turn, less documentation is needed to understand it.

**Comment by isakpulkki** [comment]
Thank you for the tips!
